In [5]:
#2d lists: list of lists
a = [[1,2,3], [4,5,6], [7,8,9]]
for row in a:
    for col in row:
        print(col, end=' ')
    print()    

1 2 3 
4 5 6 
7 8 9 


In [2]:
print(a[1])

[4, 5, 6]


In [2]:
# slicing : same as 1d list
print(a[1][2])


NameError: name 'a' is not defined

In [4]:
print(a[1:3])

[[4, 5, 6], [7, 8, 9]]


In [12]:
student_grade = [['John', 7.5], ['Mark', 7.0], ['Alice', 8.0],['Mike', 8.5],['Anna', 7.5] 
                ,['Tom', 9.5],  ['Marry', 7.5],['Bob', 7.5],  ['Jack', 8.5],['Perter', 7.5]]
#Print distinction students who have grade >=8.0
for row in student_grade:
    if row[1] >= 8.0:
        print(f'Name: {row[0]}, Grade: {row[1]}')

Name: Alice, Grade: 8.0
Name: Mike, Grade: 8.5
Name: Tom, Grade: 9.5
Name: Jack, Grade: 8.5


In [13]:
#Count how many passed student (grade >=4.0)
count = 0
for row in student_grade:
    if row[1] >=4.0:       
        count+= 1
print('Number of passed student: ', count)        


Number of passed student:  10


In [16]:
#length of row can be different
a = [[],
    [1],
    [2,3],
    [4,5,6]]
print(a, len(a))
print(a[3][2])

[[], [1], [2, 3], [4, 5, 6]] 4
6


In [23]:
#Exercise
#create 5*5 of random integer
import random as rd
a =[]
for i in range(5):
    a.append(rd.sample(range(1, 100),5))
print(a)

print(a[1:4])
print(a[1:-1])

print(a[3::])

#get max, min of nth and print then
n = int(input('Enter n: '))
print(f'Max of {n} row: {max(a[n])}, Min of {n} row: {min(a[n])}')

print('Sum of a[{n}]: {sum[(a)]}')
    




[[66, 41, 82, 78, 74], [2, 1, 74, 42, 93], [15, 25, 79, 2, 29], [51, 47, 65, 59, 15], [94, 31, 56, 24, 68]]
[[2, 1, 74, 42, 93], [15, 25, 79, 2, 29], [51, 47, 65, 59, 15]]
[[2, 1, 74, 42, 93], [15, 25, 79, 2, 29], [51, 47, 65, 59, 15]]
[[51, 47, 65, 59, 15], [94, 31, 56, 24, 68]]


IndexError: list index out of range

In [25]:
import numpy as np
# create array from list 
a = [1,2,3]
b = np.array(a)
print(a,type(a))
print(b,type(b))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [29]:
#create array from arange function ( similar range function)
a = np.arange(10)
print(a)
a = np.arange(1, 10, 2)
print(a)
a = np.arange(0, 1, 0.1)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [32]:
#create array from linspace(start, and, n(so luong cacs item duoc sinh ra)) function
a = np.linspace(0,9,10)
print(a)


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [33]:
#create array from longspace (start, end, a) function
a = np.logspace(0, 10, 11, base=2, dtype=int)
print(a)

[   1    2    4    8   16   32   64  128  256  512 1024]


In [45]:
#create array from 50 - 100, step 5
a = np.arange(50, 101, 5)
print(a)

#create 10 number from 2 to 5 
a = np.linspace(2,5,10)
print(a)

#create these numbers: 3,9,27,81, ...59049
a = np.logspace(1, 10,10 base=3, dtype=int)
print(a)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1051497775.py, line 10)

In [48]:
#create array of zeros, ones
zeros = np.zeros(10)
print(zeros)
ones = np.ones((3,3))
print(ones)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [50]:
#array operations +, - ,*, /, **, % with number
a= np.random.randint(10, 100, 5)
print(a)
print(a + 10)
print(a - 10)
print(a * 10)
print(a / 10)
print(a ** 2)
print(a % 10)

[68 89 99 53 95]
[ 78  99 109  63 105]
[58 79 89 43 85]
[680 890 990 530 950]
[6.8 8.9 9.9 5.3 9.5]
[4624 7921 9801 2809 9025]
[8 9 9 3 5]


In [51]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** b)
print(a % b)
print(a // b)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]
[1 2 3]
[0 0 0]


In [52]:
#Boolean indexing
a = np.random.randint(10, 100, 10)
b = a % 2 == 0
print(a)
print(b)
print(a[b])


[55 53 61 16 64 29 53 42 37 61]
[False False False  True  True False False  True False False]
[16 64 42]


In [ ]:
#Find numbers that has the last digit is 3
print(a[a%10]== 3)

#Find number that has the first digit is 5
print(a[a // 10]== 5)

#sum of digit >10
print(a[a] // (10 + a % 10) > 10)

In [64]:
a = np.random.randint( 10, 100, (5,5))
print(a)
#indexing list-style
print(a[2][3])
#indexing array-style
print(a[2,3])

[[32 72 78 65 87]
 [67 78 39 47 92]
 [88 92 34 12 18]
 [77 92 26 72 28]
 [32 80 99 75 10]]
12
12


In [65]:
#slide rows:
print(a[1:4])

[[67 78 39 47 92]
 [88 92 34 12 18]
 [77 92 26 72 28]]


In [66]:
#Slide columns:
print(a[:, 1:3])

[[72 78]
 [78 39]
 [92 34]
 [92 26]
 [80 99]]


In [67]:
#Slice both rows and columns
print(a[1:4, 2:4])

[[39 47]
 [34 12]
 [26 72]]


In [69]:
print(len(a), np.shape(a))


5 (5, 5)


In [71]:
b = a[0]
c = a[0:1, :]
print(b,c)
print(np.shape(b), np.shape(c))

#transpose
d =c.T
print(d, np.shape(d))

[32 72 78 65 87] [[32 72 78 65 87]]
(5,) (1, 5)
[[32]
 [72]
 [78]
 [65]
 [87]] (5, 1)
